---
- name: Prepare system
  hosts: all
  become: yes
  
  tasks:
  - name: Update
    apt:
      update_cache: yes

- name: install maven
  hosts: build
  become: yes

  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - default-jdk
      - maven
      - git
    state: latest

  - name: Clone a github repository
    git:
      repo: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/admin/boxfuse

  - name: Build war. artifact
    shell: mvn package
    args:
      chdir: /home/admin/boxfuse

- name: install tomcat server
  hosts: prod
  become: yes

  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - tomcat9
      - default-jdk
      state: latest

- name: Rsync some files
  hosts: prod
  become: yes

  tasks:
  - name: copy my file
    synchronize:
      src: /home/admin/boxfuse/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
    delegate_to: "{{groups['build'][0]}}"