---
- name: install maven
  hosts: build
  become: yes
  remote_user: root

  tasks:
  - name: Update repositories cache and install packages
    apt: 
      pkg: state=latest
      - default-jdk
      - maven
      - git
      state: latest
      update_cache: yes


  - name: Clone a repo
    ansible.builtin.git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/admin

  - name: Build war. artifact
    ansible.builtin.shell:
      cmd: mvn package
      chdir: /home/admin/boxfuse-sample-java-war-hello

- name: install db
  hosts: prod
  become: yes
  remote_user: root

  tasks:
  - name: Update repositories cache and install packages
    apt: 
      pkg: 
      - openjdk11-jre-headless
      - openjdk11
      - tomcat9
      state: latest
      update_cache: yes

    service:
      name: tomcat
      state: started

- name: Rsync some files
  hosts: prod

  tasks:
  - name: copy my file
    synchronize:
      src: /home/admin/boxfuse-sample-java-war-hello/target/*.war
      dest: /var/lib/tomcar/webapps
    delegate_to: prod